"""Create tables 2

Revision ID: 34ef9ac9fa92
Revises: e7db06248b5b
Create Date: 2026-06-20 15:54:41.521624

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "34ef9ac9fa92"
down_revision: Union[str, Sequence[str], None] = "e7db06248b5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects", "category_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects", "category_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
