"""Media set null if project deleted

Revision ID: 3f554b69e703
Revises: cf5f90952dd3
Create Date: 2026-06-25 15:08:41.893948

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3f554b69e703"
down_revision: Union[str, Sequence[str], None] = "cf5f90952dd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("project_media_project_id_fkey"), "project_media", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "project_media", "projects", ["project_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "project_media", type_="foreignkey")
    op.create_foreign_key(
        op.f("project_media_project_id_fkey"),
        "project_media",
        "projects",
        ["project_id"],
        ["id"],
    )
    # ### end Alembic commands ###
