"""add cascade delete 

Revision ID: 6d11a6d69193
Revises: f94b7849eee6
Create Date: 2026-07-01 12:51:40.999846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d11a6d69193'
down_revision: Union[str, Sequence[str], None] = 'f94b7849eee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_comments_project_id_fkey'), 'project_comments', type_='foreignkey')
    op.drop_constraint(op.f('project_comments_user_id_fkey'), 'project_comments', type_='foreignkey')
    op.create_foreign_key(None, 'project_comments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_likes_project_id_fkey'), 'project_likes', type_='foreignkey')
    op.drop_constraint(op.f('project_likes_user_id_fkey'), 'project_likes', type_='foreignkey')
    op.create_foreign_key(None, 'project_likes', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_likes', type_='foreignkey')
    op.drop_constraint(None, 'project_likes', type_='foreignkey')
    op.create_foreign_key(op.f('project_likes_user_id_fkey'), 'project_likes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('project_likes_project_id_fkey'), 'project_likes', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_comments', type_='foreignkey')
    op.drop_constraint(None, 'project_comments', type_='foreignkey')
    op.create_foreign_key(op.f('project_comments_user_id_fkey'), 'project_comments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('project_comments_project_id_fkey'), 'project_comments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###
