"""Media set null if

Revision ID: 9bab92588fed
Revises: 3f554b69e703
Create Date: 2026-06-25 15:09:42.706727

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9bab92588fed"
down_revision: Union[str, Sequence[str], None] = "3f554b69e703"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_media", "project_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_media", "project_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
