"""add university table unique name

Revision ID: d9943733e32c
Revises: f9fb3aa8ff3f
Create Date: 2026-06-29 13:32:31.419619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9943733e32c'
down_revision: Union[str, Sequence[str], None] = 'f9fb3aa8ff3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'universities', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'universities', type_='unique')
    # ### end Alembic commands ###
