"""add table roles

Revision ID: de9284eaa103
Revises: c4046eafd468
Create Date: 2026-06-27 12:54:10.047698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9284eaa103'
down_revision: Union[str, Sequence[str], None] = 'c4046eafd468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('member_roles', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'member_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('member_roles', 'role')
    op.add_column('project_invites', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project_invites', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_invites', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_invites', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_invites', type_='foreignkey')
    op.drop_column('project_invites', 'role_id')
    op.add_column('member_roles', sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'member_roles', type_='foreignkey')
    op.drop_column('member_roles', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
