"""add university table

Revision ID: f9fb3aa8ff3f
Revises: 4d1df288a9a1
Create Date: 2026-06-29 13:27:15.844916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fb3aa8ff3f'
down_revision: Union[str, Sequence[str], None] = '4d1df288a9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('projects', sa.Column('university_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'universities', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'university_id')
    op.drop_table('universities')
    # ### end Alembic commands ###
